# Generated by Django 3.1.5 on 2021-10-10 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodePlay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='submission_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 0, 30, 29, 701455)),
        ),
        migrations.AlterField(
            model_name='sessionpool',
            name='expireAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 0, 30, 29, 695462)),
        ),
    ]
