# Generated by Django 3.1.5 on 2021-10-09 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodePlay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionpool',
            name='expireAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 8, 40, 1, 94824)),
        ),
    ]
