# Generated by Django 3.1.5 on 2021-10-10 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodePlay', '0004_auto_20211010_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='submission_time',
            field=models.BigIntegerField(default=1633857547.518794),
        ),
        migrations.AlterField(
            model_name='sessionpool',
            name='expireAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 17, 19, 7, 509736)),
        ),
    ]
