# Generated by Django 3.1.5 on 2021-11-09 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodePlay', '0005_auto_20211010_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='voted_people',
            field=models.ManyToManyField(related_name='scheme_voted', to='CodePlay.User'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='submission_time',
            field=models.BigIntegerField(default=1636420786.997115),
        ),
        migrations.AlterField(
            model_name='sessionpool',
            name='expireAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 9, 19, 46, 992114)),
        ),
    ]
